docs/usage/scopes.md
The documentation was missing a word in the title of the example on how to use the orWhereTranslationLike method.
=> Typo: add word to title of example on how to use orWhereTranslationLike

.circleci/config.yml, src/Translatable/Traits/Relationship.php
Small refactoring for improve readability
=> Refactoring 

src/Translatable/Translatable.php
Currently, only one fallback locale can be used and it has to be predetermined in config. Auto fallback means looping through available locales (in configuration order) and using the first available translation. I believe this is much more realistic than using a specified fallback locale.
This commit generates no conflicts or unwanted operation, as this feature only operates if fallback_locale in configuration is set to null (null value is not used for anything currently). Way of loading translations neither affected.
=> Add auto fallback feature

.codeclimate.yml, .gitignore, src/Translatable/Validation/RuleFactory.php, src/config/translatable.php, tests/TestsBase.php, tests/ValidationTest.php
=> rule factory

src/Translatable/Translatable.php
Most times we need only one translation, and don't need to load all translations of model.
We can't use this now:
```
$models = Model::with('translation')->get();
foreach($models as $model){
echo $model->title;
}
```
Method `getTranslationByLocaleKey()` ignores `translation()` relation and always use `translations()` relation, which loads all translations instead of load only one, that we need.
=> Allows to load `translation` relation instead of load all `translations`.

.circleci/config.yml, composer.json, tests/LocalesTest.php, tests/ScopesTest.php, tests/TestCoreModelExtension.php, tests/TestsBase.php, tests/TranslatableTest.php, tests/ValidationTest.php
=> add laravel 6

src/Translatable/Traits/Scopes.php, tests/ScopesTest.php
The issue was that by doing a `join` it didn't join the records that are missing translations in the desired locale. By doing a `leftJoin` we get that records anyway and, adding the `orderByRaw`, we ensure to get first those records translated in the `locale` we want.
I'm sure it will need further modifications, let me know of any required change @Gummibeer 
Fixes #71
=> Get all translations when ordering by locale

.travis.yml, composer.json
Laravel 5.6 & 5.7 are out of support. They would require adjusted tests - so support is dropped now.
https://laravel.com/docs/master/releases
#75
=> drop outdated laravel versions

src/Translatable/Contracts/Translatable.php, src/Translatable/Translatable.php, tests/TranslatableTest.php, tests/migrations/2013_11_28_152610_create_tables.php
After talking to @Gummibeer, we decided to add this feature as a model-level property.
Iterating over each model will preserve the soft-deletes or other custom code the user could have written overriding `delete` method on the models.
Fixes #85
=> Delete translations on cascade

docs/usage/methods.md, src/Translatable/Translatable.php, tests/TranslatableTest.php
Hi, I thought it would be useful to have a convenience method that throws a ModelNotFoundException if a translation does not exist, mimicking the behaviour of Eloquent's findOrFail(). Thanks for the project :smile:
=> Added translateOrFail method to translatable trait

tests/TranslatableTest.php
I was checking #121 on local and I saw that the test was actually comparing against `null` because the missing `->save()` call. 
I'm not fixing any bug here, but just checking that the replicated translation model actually points to the replicated model.
=> Ensure replicated translations contains the replicated model id

.gitattributes
`git archive fixes | gzip > fixes-branch.tgz` where `fixes` is the branch name
to have a try of the effect on composer installs you can use my lib https://github.com/williamdes/mariadb-mysql-kbs
=> Add .gitattributes to exclude some files from production environments

.github/workflows/run-tests.yml, composer.json
This pr adds laravel 8.0 support. 
- I added the version for the required composer dependencies and added the laravel version `8.*` to the `run-test.yml` workflow. 
- Additionally requiring legacy factories for `8.*` tests.
=> Laravel 8.0 support

docs/usage/installation.md
Updated the documentation to reference the ability to change `$translationForeignKey` property because it was not mentioned except in this issue.
[using custom foreign key for translation table](https://github.com/Astrotomic/laravel-translatable/issues/117)
=> added the ability to change $translationForeignKey property 

.github/dependabot.yml
=> feat(github-actions): Dependabot Github Actions update check

.gitattributes
Reduced dist size from 3.9M to 72K.
https://php.watch/articles/composer-gitattributes
=> Update .gitattributes to reduce dist size

src/Translatable/Traits/Scopes.php
Under some circonstance we want to preview some data in language that are not the current one. But however want to benefit the fallback mechanism.
This PR add ability to specify the locale we want. 
```php
Model::query()->withTranslation("de")->get();
```
As the param is optional, this PR doesn't include breaking changes
=> Accept $locale in withTranslation scope

src/Translatable/Translatable.php
If we do
```php
$tr = $model->translateOrNew('en');
$tr->some_field = 'abc';
$tr->save();
```
We get a query exception (`Field ..._id doesn't have a default value`) because the package is not setting the relation key
This PR fixes the issue
=> Fix new translation is missing the relation id for saving

tests/TranslatableTest.php
Found a misspelling.
BTW "Peas" in Ukrainian is "Горох" (horokh).
=> Fix a typo in TranslatableTest

docs/package/scopes.md
Description for translated() scope is wrong.
If I have no translation, translated() scope is returning nothing. But with at least one translation translated() scope return post
=> Description for translated() scope is wrong

tests/TranslatableTest.php
This test temporary failed while I was writing the test for #424, and took my attention. I think if the original implementation is called from the overrided method the test can catch some change on the original method that affects the behaviour, but I'm not sure about your opinion, so I preferred to create a separated PR for this change so you can accept or reject it independently.
=> Call original implementation on numeric translated tests

tests/TranslatableTest.php
The change introduced in PR #418 can be removed without any test failing.
=> Add missing test for saving translations standalone

README.md, docs/README.md, src/Translatable/Translatable.php, src/config/translatable.php, tests/TranslatableTest.php
**Description:**
Adding the ability to wrap multiple translations when creating new records.
**Changes:**
Added `translations_wrapper`   config to allow user to set a custom wrapper name.
**Purpose:**
When working with DTOs, we've found it useful to be able to wrap all the translations into a specific property when creating multiple records at once. 
**Benefits:**
Facilitates to create/convert the DTOs and use them for model creation/update.
**Usage:**
Developers can now set a custom wrapper for multiple creation and use it in the following way: 
You may define a wrapper property when creating new translations. Set the `translations_wrapper` property in translatable config file:
```php
'translations_wrapper' => 'translations',
```
Then just wrap multiple locales using that property: …
=> Allow to use a wrapper when creating multiple translations

src/Translatable/Translatable.php, tests/TranslatableTest.php
When using the `translations_wrapper` config option in combination with a model factory, an SQL error is thrown. 
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 table vegetables has no column named _translation_wrapper (Connection: testing, SQL: insert into "vegetables" ("quantity", "_translation_wrapper", "updated_at", "created_at") values (5, ?, 2024-09-16 08:52:41, 2024-09-16 08:52:41))
```
This has to do with the fact that eloquent model factories unguard the model before performing a mass assignment. The wrapped attribute is not removed from the attributes array so an attempt is made to insert that into the base model as wel.
This MR fixes that issue. I have accompanied the proposed code with a test to demonstrate its proper functioning.
=> Fix wrapped mass assignment with unguarded models
